### ISSUE TITLE
一覧画面にページング処理を実装する

### ISSUE THREAD

**Issue by erikka-22** [cfj-afterpillsearch/search-frontend#101]
一覧画面にページング処理を実装する

**Comment by tanimuranaomichi** [comment]
https://daisyui.com/components/pagination/

**Comment by erikka-22** [comment]
・画面幅に対してボタン群の幅に違和感が無いように
・現在見ているページが何ページ目なのかがわかるように

**Comment by tanimuranaomichi** [comment]
![PXL_20231014_050817703.jpg](https://github.com/cfj-afterpillsearch/search-frontend/assets/79921660/c94313b1-c65e-42d6-ad17-6abdf69e7af5)

**Comment by erikka-22** [comment]
23/10/30 MTG で挙がったタスク

- [ ]  アドレスバーに表示されるURLにページパラメータを追加
- [ ]  addressの場合、ページパラメータを含むURLを指定したら、指定されたページの結果が返るようにする。
    - [ ]  addressの場合、存在しないページ数がパラメータで渡ってくるときはpage=1に置き換えて結果を表示
- [ ]  current-locationの場合、ページパラメータを含むURLが渡ってきたときも、パラメータは無視して常にpage=1の結果を表示する。
- [ ]  disableボタンの背景色をactiveでないボタンと同じ色にする
- [ ]  ボタン文字列のフォント、もう少し細いものにするとよいかも
- [ ]  1ページあたり20件は少し多い→1ページあたり10件に変更
