### ISSUE TITLE
ホームページが存在しない医療機関/薬局のホームページボタンをクリック/タップした時の挙動を固める

### ISSUE THREAD

**Issue by erikka-22** [cfj-afterpillsearch/search-frontend#33]
ホームページが存在しない医療機関/薬局のホームページボタンをクリック/タップした時は、画面遷移せずにアラートを表示する？

**Comment by osappy** [comment]
Mtg.にて下記のように決めた。

- ホームページボタン→検索ボタンに変更。
    - Google検索ボタンをクリック→病院名でGoogle検索した結果に飛ぶ
