### ISSUE TITLE
Google Analyticsの設定

### ISSUE THREAD

**Issue by osappy** [cfj-afterpillsearch/search-frontend#54]
- [x] GAの用意 > osappy
- [ ] Frontendに埋め込む
- [ ] ちゃんとデータが取れているか確認する

**Comment by osappy** [comment]
>`<head>`に入れる

もしかしたらAngularのプラグインにあるかもなので、それを使って単純にコピペは避けてください。
できれば、GAの測定IDは環境変数で渡したいです。

あと、さっき作ったafterpilljpプロパティは、`https://afterpill.jp`からのアクセスしか受け取らないのではないかと思います。つまり、検証するにはmainブランチに直接デプロイする必要が出てきてしまいます。

それを避けるために開発環境用にafterpilljp-devプロパティとGA検証用のブランチ`ga`を作りました。

`ga`ブランチにPushすれば、自動的に`https://ga--afterpill-search-dev.netlify.app/`にデプロイされます。(NetlifyのBranch Deployという機能です)
そしてafterpilljp-devプロパティは`https://ga--afterpill-search-dev.netlify.app/`というURLからしかデータを受信しない設定になっています。
GAの検証を行うときは`ga`ブランチを使ってください。

**Comment by tanimuranaomichi** [comment]
https://www.npmjs.com/package/angular-google-tag-manager

**Comment by osappy** [comment]
Google Tag Managerを使う方針で進める。
でも難しそうだったら、Google Analyticsをを使ってよい。

**Comment by erikka-22** [comment]
https://support.google.com/analytics/answer/12229021?hl=en
https://www.npmjs.com/package/angular-google-tag-manager

**Comment by erikka-22** [comment]
@osappy 
設定と動作確認のために、google tag manager のタグの管理権限だけでなく、google tag manager のアカウントへのアクセス権限もいただきたいです！

**Comment by osappy** [comment]
@erikka-22 @tanimuranaomichi 
GTMのメンバーに招待しましたのでメールをご確認ください！

**Comment by erikka-22** [comment]
@osappy アカウントにアクセスできることを確認しました！ありがとうございます！

**Comment by erikka-22** [comment]
@osappy Googleアナリティクスの、開発環境用のafterpilljp-devプロパティの測定IDを教えていただきたいです！

**Comment by osappy** [comment]
@erikka-22 
すみません。devのほうに権限が付与されていませんでした。
権限付与したので下記のURLから取得してください。
https://analytics.google.com/analytics/web/#/a280576951p401305793/admin/streams/table/

**Comment by erikka-22** [comment]
@osappy ありがとうございます！

**Comment by erikka-22** [comment]
@osappy GTMのafterpill-searchのコンテナに、GAのafterpilljp-devプロパティの測定IDを指定したタグを追加で作成してもよいでしょうか？
それとも、devの方はafterpill-search-devのコンテナにタグを設定するのがよいでしょうか？

**Comment by osappy** [comment]
@erikka-22 
本番環境には、`afterpill-search`コンテナを使って`afterpill.jp`プロパティの測定IDが適用されるようにしてください。
本番環境以外は、`afterpill-search-dev`コンテナを使って`afterpill.jp-dev`プロパティの測定IDが適用されるようにしてください。

**Comment by erikka-22** [comment]
@osappy 了解しました！`afterpill-search-dev`コンテナに`afterpill.jp-dev`プロパティの測定IDを指定したタグを追加します！

**Comment by erikka-22** [comment]
@osappy 
GTMのコンテナIDを環境変数で指定しています。
netlifyでgaブランチをデプロイする際に参照される環境変数に
`GOOGLE_TAG_MANAGER_ID=GTMで始まるafterpill-search-devコンテナのコンテナID`
を追加していただきたいです！

**Comment by osappy** [comment]
@erikka-22 
了解です。
今すぐやります。

**Comment by osappy** [comment]
@erikka-22 
環境変数ですが、使っているライブラリの仕様として`NG_APP_`プレフィックスを付けないと読み込まないため、`NG_APP_GOOGLE_TAG_MANAGER_ID`で設定しました。
https://www.npmjs.com/package/@ngx-env/builder#ng_app_-or-custom-prefix

環境変数名の変更のほどよろしくお願いします。

**Comment by erikka-22** [comment]
@osappy ありがとうございます！環境変数名の変更、了解しました！

**Comment by erikka-22** [comment]
googleタグマネージャのアカウントafterpill-searchとafterpill-search-devで変更を公開しました！
