### ISSUE TITLE
Loading中の画面

### ISSUE THREAD

**Issue by osappy** [cfj-afterpillsearch/search-frontend#59]
検索画面を押すと、サーバーから値が返却されるまで下記のような表示になる。

![image](https://github.com/cfj-afterpillsearch/search-frontend/assets/904929/34ccb9d1-ea2d-4e33-96b4-a2c3ca1bbac9)

**Comment by tanimuranaomichi** [comment]
以下2つを実装
- 「検索中です」みたいな文言
- ローディングのくるくる

**Comment by tanimuranaomichi** [comment]
#62 に統合した
