### ISSUE TITLE
検索結果ページ変更

### ISSUE THREAD

**Issue by tanimuranaomichi** [cfj-afterpillsearch/search-frontend#68]

**Comment by tanimuranaomichi** [comment]
@erikka-22 
すいません、あんまり話についていけていないです
バックエンド側でhas_emergency_contactというパラメータがあるっぽいのですが、それを使うのは無しなんですか？

**Comment by erikka-22** [comment]
has_emergency_contact の存在を見落としていました！ありがとうございます！

これは、現行ピルにゃんの時間外対応検索の指定条件

- 有
- 有（仮）
- 未回答
- 無

のいずれかの値が入っているパラメータだと思ってよいのでしょうか...？？

**Comment by tanimuranaomichi** [comment]
> has_emergency_contact、openapi.yamlには記述がありますが未実装ですかね...？？

たぶんそんな気がします！

**Comment by osappy** [comment]
うーん、なんでか薬局のエンドポイントに時間外対応の対応を追加するタスクが完全に抜け落ちてました。すみません。

>指定なしの場合：パラメータなし
>有の場合：クエリパラメータでis_out_of_hours=1 を渡す
>無の場合：クエリパラメータでis_out_of_hours=0 を渡す

基本的に @erikka-22 さんの提案通りでよいと思いますので、このパラメータ名で実装します。
ただ「無」を選ぶメリットがないと思うので、「指定なし」「有」の2つの選択肢でよいと思いました。Figmaのほう直しますね。


>has_emergency_contact

openapi.yamlに残ってしまっていましたか。すみません。
途中まで実装して、`emergency_contact_phone`に値が入っているか入っていないかで判別できると思い実装していません。
時間外対応の判別は`emergency_contact_phone`を見て判断してください。


あとFigmaへのコメントですが全てAgreeなので、 @erikka-22 さんの提案通りに実装してください。
実装したあとFigmaを実装したとおりに修正してもらえると助かります。

**Comment by osappy** [comment]
@erikka-22 
薬局の時間外対応のクエリパラメータの実装できました。
下記のように使ってください。現在、開発環境のみデプロイしています。

時間外対応が指定なしの場合、
/api/v1/search/address/pharmacies?todofuken=東京都&shikuchoson=新宿区

時間外対応が有の場合、
/api/v1/search/address/pharmacies?todofuken=東京都&shikuchoson=新宿区&is_out_of_hours=1
