### ISSUE TITLE
日曜診療・祝日診療で△と表示すべきところが◯になっている

### ISSUE THREAD

**Issue by erikka-22** [cfj-afterpillsearch/search-frontend#79]
https://cfj.slack.com/archives/C05AGEKGUSU/p1695438476686329?thread_ts=1695437885.724139&cid=C05AGEKGUSU
https://cfj.slack.com/archives/C05AGEKGUSU/p1695438802871809?thread_ts=1695437885.724139&cid=C05AGEKGUSU
https://cfj.slack.com/archives/C05AGEKGUSU/p1695440160112019?thread_ts=1695437885.724139&cid=C05AGEKGUSU

**Comment by erikka-22** [comment]
しらすさんより

ごめん、いま、システム検索して気づいたのだけど、日曜祝日の△を選んだ場合、それよりも条件のよい○も、同時に検索されて表示されないといけないのではないかとおもってきた…

https://cfj.slack.com/archives/C05AGEKGUSU/p1695451038052919

**Comment by tanimuranaomichi** [comment]
> しらすさんより
> 
> ごめん、いま、システム検索して気づいたのだけど、日曜祝日の△を選んだ場合、それよりも条件のよい○も、同時に検索されて表示されないといけないのではないかとおもってきた…
> 
> https://cfj.slack.com/archives/C05AGEKGUSU/p1695451038052919

こちらは別issue #93 で扱うため、本issueでは扱わない
